# Generated by Django 5.2 on 2025-05-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PythonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="ファイル名", max_length=255)),
                (
                    "original_name",
                    models.CharField(
                        help_text="アップロード時のオリジナルファイル名", max_length=255
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="実際のファイル", upload_to="python_files/%Y/%m/%d/"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="ファイルの説明", null=True),
                ),
                (
                    "file_size",
                    models.IntegerField(help_text="ファイルサイズ（バイト）"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_python_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Python File",
                "verbose_name_plural": "Python Files",
                "ordering": ["-created_at"],
            },
        ),
    ]
