# Generated by Django 5.2 on 2025-05-25 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeDefinition",
            fields=[
                (
                    "node_definition_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_name", models.CharField(max_length=255)),
                ("python_class_name", models.CharField(max_length=255)),
                ("module_path", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
                ("input_schema", models.JSONField(default=dict)),
                ("output_schema", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "node_definitions",
            },
        ),
    ]
