# Generated by Django 5.2 on 2025-07-14 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0002_nodedefinition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="NodeDefinition",
        ),
        migrations.AlterModelOptions(
            name="pythonfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="pythonfile",
            name="original_name",
        ),
        migrations.AddField(
            model_name="pythonfile",
            name="analysis_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pythonfile",
            name="file_content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="pythonfile",
            name="file_hash",
            field=models.CharField(default="default", max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="pythonfile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pythonfile",
            name="is_analyzed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pythonfile",
            name="node_classes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="pythonfile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pythonfile",
            name="file",
            field=models.FileField(upload_to="python_files/"),
        ),
        migrations.AlterField(
            model_name="pythonfile",
            name="file_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pythonfile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pythonfile",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pythonfile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterModelTable(
            name="pythonfile",
            table="python_files",
        ),
    ]
